### ISSUE TITLE
Question about training dataset processing and training code

### ISSUE THREAD

**Issue by datewangshao** [SaFoLab-WISC/Dolphins#6]
Hello,
Thank you for your hard work on this project! I am currently exploring the training pipeline and had a few questions regarding the dataset processing and training code.

Could you provide more details on how the training dataset is prepared or processed before being used in training? Are there any specific steps or preprocessing scripts you recommend?

I would also appreciate some insights into the structure of the training code. For example, are there certain key functions or modules I should focus on for understanding the training loop?

Thank you for your time, and I look forward to your response!

Best regards,

**Comment by gray311** [comment]
Hi, thank you for your interest in our work. Regarding your questions about the dataset preparation:

1. data process: our dataset code can be found in this [link](https://github.com/SaFoLab-WISC/Dolphins/blob/a956073d4266d59c9b3061aa6f265b717ee15eeb/dataset_utils/bddx_dataset.py). We use the preprocessed video data provided by ADAPT, and you can download the data from this [link](https://github.com/jxbbb/ADAPT?tab=readme-ov-file#dataset-preparation). As for the instruction data, you can download in this [link](https://drive.google.com/file/d/1gmCTyjdoiI4qTknyhatAVMDVuqX3nu4l/view). I think the one thing you need to notice when processing BDDX data is to [compute control signals](https://github.com/SaFoLab-WISC/Dolphins/blob/a956073d4266d59c9b3061aa6f265b717ee15eeb/dataset_utils/bddx_dataset.py#L186). Because the duration of each Behavior in BDDX is not the same, some behaviors like turn left will only last for 2s, while drive forward will last for 30s, so you need to pay attention to your control signals to match with the frames you provided when you process the data. Or you can provide control signals per second, either way is fine, but you need to be consistent.

**Comment by gray311** [comment]
Regarding your questions about the training process:

1. Actually, I do not recommend that you continue using [OpenFlamingo](https://github.com/mlfoundations/open_flamingo) as your training framework like we did, because it hasn't been updated for a long time. OpenFlamingo has a significant performance gap compared to current VLMs, such as [LLaVA-Next](https://github.com/LLaVA-VL/LLaVA-NeXT) and [VILA](https://github.com/NVlabs/VILA). Therefore, I think you can refer to VILA's training process instead. You only need to process the BDDX dataset into its training format within the [dataset](https://github.com/NVlabs/VILA/blob/1fa9e0881a2425d8a0778d747f5b0336d27b2af8/llava/data/dataset.py), and you'll be ready to start training.

**Comment by gray311** [comment]
Please feel free to contact me if you have any other questions and you can directly send emails to me: g19myz@gmail.com

**Comment by datewangshao** [comment]
Hi [gray311](https://github.com/gray311),

Thank you so much for your prompt and helpful response! I really appreciate your suggestion and will try it out as soon as possible. I’ll keep you updated on how it goes.

I also had a quick question: in the [dataset_config](https://github.com/SaFoLab-WISC/Dolphins/blob/a956073d4266d59c9b3061aa6f265b717ee15eeb/configs/dataset_config.py) file, I found only one entry in the dictionary, and I didn't see any configuration related to the BDD-X dataset. Could you please point me in the right direction for where I might find the BDD-X dataset configuration?

**Comment by datewangshao** [comment]
> Please feel free to contact me if you have any other questions and you can directly send emails to me: [g19myz@gmail.com](mailto:g19myz@gmail.com)

Hi [gray311](https://github.com/gray311),

Thank you so much for your prompt and helpful response! I really appreciate your suggestion and will try it out as soon as possible. I’ll keep you updated on how it goes.

I also had a quick question: in the [dataset_config](https://github.com/SaFoLab-WISC/Dolphins/blob/a956073d4266d59c9b3061aa6f265b717ee15eeb/configs/dataset_config.py) file, I found only one entry in the dictionary, and I didn't see any configuration related to the BDD-X dataset. Could you please point me in the right direction for where I might find the BDD-X dataset configuration?

**Comment by gray311** [comment]
You can refer to this [line](https://github.com/SaFoLab-WISC/Dolphins/blob/a956073d4266d59c9b3061aa6f265b717ee15eeb/dataset_utils/bddx_dataset.py#L504)

**Comment by datewangshao** [comment]
> You can refer to this [line](https://github.com/SaFoLab-WISC/Dolphins/blob/a956073d4266d59c9b3061aa6f265b717ee15eeb/dataset_utils/bddx_dataset.py#L504)

Thank you for your response! I really appreciate your input and will do my best to work on it.
